application: jesseshieh-jshieh
version: 1
runtime: python
api_version: 1

handlers:

# static directories
- url: /stylesheets
  static_dir: stylesheets
- url: /javascript
  static_dir: javascript
- url: /images
  static_dir: images
- url: /pub
  static_dir: pub

# static files
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

# pages
- url: /
  script: main.py
- url: /resume
  script: main.py
- url: /projects
  script: main.py
- url: /contact
  script: main.py

# taskqueue tasks
- url: /tasks/email/me
  script: main.py

# default catch-all
- url: .*
  script: main.py
